import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Diasan III",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-gray-600 font-body">
        <div className="">
          <Navbar />
          <main className="px-16 py-6 bg-gray-100 md:col-span-5">
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
